from typing import Dict

MAPA_APPS: Dict[str, str] = {
    "chrome": "Google Chrome",
    "google chrome": "Google Chrome",
    "chromium": "Chromium",
    "firefox": "Firefox",
    "mozilla firefox": "Firefox",
    "edge": "Microsoft Edge",
    "microsoft edge": "Microsoft Edge",
    "opera": "Opera",
    "brave": "Brave",
    "browser": "Google Chrome",
    "navegador": "Google Chrome",
    "nav": "Google Chrome",
    "vscode": "Visual Studio Code",
    "visual studio code": "Visual Studio Code",
    "code": "Visual Studio Code",
    "sublime": "Sublime Text",
    "sublime text": "Sublime Text",
    "notepad": "Notepad++",
    "cmd": "Prompt de Comando",
    "prompt": "Prompt de Comando",
    "terminal": "Windows Terminal",
    "powershell": "PowerShell",
    "windows powershell": "PowerShell",
    "explorer": "Explorador de Arquivos",
    "explorador": "Explorador de Arquivos",
    "explorador arquivos": "Explorador de Arquivos",
    "arquivos": "Explorador de Arquivos",
    "spotify": "Spotify",
    "vlc": "VLC media player",
    "vlc media player": "VLC media player",
    "player": "VLC media player",
    "calculadora": "Calculadora",
    "calc": "Calculadora",
    "bloco de notas": "Bloco de notas",
    "bloco notas": "Bloco de notas",
    "notas": "Bloco de notas",
    "calendario": "Calendario",
    "configuracoes": "Configurações",
    "config": "Configurações",
    "painel de controle": "Painel de Controle",
    "controle": "Painel de Controle",
    "discord": "Discord",
    "teams": "Microsoft Teams",
    "microsoft teams": "Microsoft Teams",
    "slack": "Slack",
    "telegram": "Telegram Desktop",
    "whatsapp": "WhatsApp",
    "zoom": "Zoom",
    "word": "Microsoft Word",
    "excel": "Microsoft Excel",
    "powerpoint": "Microsoft PowerPoint",
    "outlook": "Microsoft Outlook",
    "onenote": "Microsoft OneNote",
}
